/*
  MODULE 1 — SCHEMA, TABLES, KEYS AND CONSTRAINTS
  Connect to techstore_db before running this file.
*/

CREATE SCHEMA IF NOT EXISTS sales;
CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE IF NOT EXISTS sales.categories (
    category_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar(80) NOT NULL UNIQUE,
    description   text
);

CREATE TABLE IF NOT EXISTS sales.products (
    product_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   integer NOT NULL
                  REFERENCES sales.categories(category_id)
                  ON UPDATE CASCADE ON DELETE RESTRICT,
    sku           varchar(20) NOT NULL UNIQUE,
    product_name  varchar(120) NOT NULL,
    unit_price    numeric(10,2) NOT NULL CHECK (unit_price > 0),
    stock_qty     integer NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    active        boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS sales.customers (
    customer_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     varchar(120) NOT NULL,
    email         varchar(255) NOT NULL,
    phone         varchar(30),
    city          varchar(80),
    registered_at timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_email_basic CHECK (position('@' IN email) > 1)
);

CREATE TABLE IF NOT EXISTS sales.orders (
    order_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no      varchar(20) NOT NULL UNIQUE,
    customer_id   bigint NOT NULL
                  REFERENCES sales.customers(customer_id)
                  ON DELETE RESTRICT,
    order_date    date NOT NULL DEFAULT current_date,
    status        varchar(15) NOT NULL DEFAULT 'PENDING',
    notes         text,
    created_at    timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT ck_orders_status
        CHECK (status IN ('PENDING','PAID','PROCESSING','SHIPPED','CANCELLED'))
);

CREATE TABLE IF NOT EXISTS sales.order_items (
    order_id      bigint NOT NULL
                  REFERENCES sales.orders(order_id) ON DELETE CASCADE,
    product_id    integer NOT NULL
                  REFERENCES sales.products(product_id) ON DELETE RESTRICT,
    quantity      integer NOT NULL CHECK (quantity > 0),
    unit_price    numeric(10,2) NOT NULL CHECK (unit_price > 0),
    discount      numeric(10,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
    line_total    numeric(12,2)
                  GENERATED ALWAYS AS ((quantity * unit_price) - discount) STORED,
    PRIMARY KEY (order_id, product_id),
    CONSTRAINT ck_order_items_discount
        CHECK (discount <= quantity * unit_price)
);

CREATE TABLE IF NOT EXISTS sales.payments (
    payment_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint NOT NULL
                  REFERENCES sales.orders(order_id) ON DELETE CASCADE,
    payment_date  timestamptz NOT NULL DEFAULT current_timestamp,
    amount        numeric(12,2) NOT NULL CHECK (amount > 0),
    method        varchar(20) NOT NULL,
    reference_no  varchar(80) UNIQUE,
    CONSTRAINT ck_payments_method
        CHECK (method IN ('CARD','FPX','EWALLET','BANK_TRANSFER','CASH'))
);

CREATE TABLE IF NOT EXISTS audit.product_price_log (
    audit_id      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id    integer NOT NULL,
    old_price     numeric(10,2) NOT NULL,
    new_price     numeric(10,2) NOT NULL,
    changed_at    timestamptz NOT NULL DEFAULT current_timestamp,
    changed_by    text NOT NULL DEFAULT current_user
);

COMMENT ON TABLE sales.order_items IS
'Snapshot prices are stored here so historical totals do not change when product prices change.';

-- VERIFY
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema IN ('sales', 'audit')
ORDER BY table_schema, table_name;

